# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: APsystems EZ1 - Python Library
theme:
  name: material

plugins:
- search
- mkdocstrings:
    handlers:
      python:
        options:
          docstring_style: sphinx